import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";
import {
  bytesToHex,
  hexToBytes,
  proveVRF,
  publicKeyFromSeed,
  verifyVRF,
  vrfProofToHash,
} from "../src";

/**
 * Byte-exact RFC 9381 ECVRF-EDWARDS25519-SHA512-TAI interop tests.
 *
 * Fixtures generated by `tooling/witnet-vector-gen` (a Rust binary using the
 * `vrf-rfc9381` crate, which is an independent reference implementation of
 * RFC 9381). Each vector contains (sk, alpha) inputs and (pk, proof, beta)
 * outputs computed by the reference implementation.
 *
 * If our JS prove/verify/proof_to_hash produce byte-identical outputs to the
 * reference for the same inputs, the implementations are interoperable per
 * RFC 9381.
 *
 * Regenerate fixtures by running, from the repo root:
 *   (cd tooling/witnet-vector-gen && cargo run --release --quiet) > \
 *     packages/ecvrf/test/fixtures/rfc9381-vectors.json
 */
interface RfcVector {
  label: string;
  sk: string;
  pk: string;
  alpha: string;
  proof: string;
  beta: string;
}

const fixturePath = path.join(__dirname, "fixtures", "rfc9381-vectors.json");
const vectors: RfcVector[] = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

describe("RFC 9381 ECVRF-EDWARDS25519-SHA512-TAI interop (vs vrf-rfc9381 Rust crate)", () => {
  it("loaded at least one fixture", () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    describe(v.label, () => {
      it("derives the same public key", () => {
        const pk = publicKeyFromSeed(hexToBytes(v.sk));
        expect(bytesToHex(pk)).toBe(v.pk);
      });

      it("produces a byte-identical proof", () => {
        const { proof } = proveVRF(hexToBytes(v.sk), hexToBytes(v.alpha));
        expect(bytesToHex(proof)).toBe(v.proof);
      });

      it("verifies the reference proof against the reference pk", () => {
        const ok = verifyVRF(
          hexToBytes(v.pk),
          hexToBytes(v.alpha),
          hexToBytes(v.proof),
        );
        expect(ok).toBe(true);
      });

      it("produces a byte-identical beta from the reference proof", () => {
        const beta = vrfProofToHash(hexToBytes(v.proof));
        expect(bytesToHex(beta)).toBe(v.beta);
      });
    });
  }
});
