packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@stellar/stellar-sdk': true
  blake-hash: true
  bufferutil: true
  esbuild: true
  protobufjs: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
